project_name: "maskformer_at_phenobench"
experiment_name: "leaf_instance_crop_segmentation"
seed: 101
overfit: False
inference:
  threshold: 0.5
  mask_threshold: 0.5
  overlap_mask_area_threshold: 0.8
model:
  pretrained: facebook/mask2former-swin-large-coco-panoptic
  ckpt_path:  None
  mode: panoptic
  ema_decay: 1.0
data:
  root: "../PhenoBench" # Path to the root folder of the dataset
  target_type: leaf_instances
  img_size: 512
  num_workers: 4
  ds_mean: [123.675, 116.280, 103.530]
  ds_std: [58.395, 57.120, 57.375]
  p_randomresizedcrop: 1.0
  p_horizontalflip: 0.5
  p_verticalflip: 0.5
  p_rgbshift: 1.0
  p_randombrightnesscontrast: 1.0
  p_blur: 0.3
  p_rotate: 0.5
  blackout: True
training:
  max_steps: 12000 
  log_every_n_steps: 20
  check_val_every_n_epoch: 3
  do_val_loss: True
  do_val_metrics: True
  batch_size: 6
  accumulate_grad_batches: 4
  gradient_clip_val: 0.01
optimizer:
  name: AdamW
  lr: 0.0001
  encoder_lr_factor: 0.1
  weight_decay: 0.05
scheduler:
  name: PolynomialLR
  T_0: 10
  T_mult: 1
  milestones: [9000,]
  gamma: 0.1
  warmup_steps: 0
  warmup_start_multiplier: 0.1
logging:
  output_folder: "../output_train" # Path to the log folder

